# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::CreateDiaryEntryInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::CreateDiaryEntryInputType`.


class Types::CreateDiaryEntryInputType
  sig { returns(::Translation::Language) }
  def language; end

  sig { returns(::Translation::Language) }
  def notes_language; end
end
