# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::DeleteDiaryEntryInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::DeleteDiaryEntryInputType`.


class Types::DeleteDiaryEntryInputType
  sig { returns(::String) }
  def id; end
end
