# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::ReplyToDiaryThreadInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::ReplyToDiaryThreadInputType`.


class Types::ReplyToDiaryThreadInputType
  sig { returns(::String) }
  def body; end

  sig { returns(::String) }
  def thread_id; end
end
