# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::RequestDiaryHintInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::RequestDiaryHintInputType`.


class Types::RequestDiaryHintInputType
  sig { returns(::String) }
  def thread_id; end
end
