# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::ResolveDiaryThreadInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::ResolveDiaryThreadInputType`.


class Types::ResolveDiaryThreadInputType
  sig { returns(T::Boolean) }
  def resolved; end

  sig { returns(::String) }
  def thread_id; end
end
