# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::ReviewDiaryEntryInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::ReviewDiaryEntryInputType`.


class Types::ReviewDiaryEntryInputType
  sig { returns(::String) }
  def body; end

  sig { returns(::String) }
  def id; end
end
