# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::StartDiaryHelpThreadInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::StartDiaryHelpThreadInputType`.


class Types::StartDiaryHelpThreadInputType
  sig { returns(::String) }
  def entry_id; end

  sig { returns(::String) }
  def question; end
end
