# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::SuggestDiaryTopicsInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::SuggestDiaryTopicsInputType`.


class Types::SuggestDiaryTopicsInputType
  sig { returns(T.nilable(::String)) }
  def body; end

  sig { returns(::Translation::Language) }
  def language; end

  sig { returns(::Translation::Language) }
  def notes_language; end
end
