# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::TranslateInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::TranslateInputType`.


class Types::TranslateInputType
  sig { returns(T.nilable(::String)) }
  def context; end

  sig { returns(T.nilable(::Translation::GlossLevel)) }
  def gloss_level; end

  sig { returns(::Translation::Language) }
  def source_language; end

  sig { returns(::String) }
  def source_text; end

  sig { returns(::Translation::Language) }
  def target_language; end
end
