# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::UpdateDiaryEntryInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::UpdateDiaryEntryInputType`.


class Types::UpdateDiaryEntryInputType
  sig { returns(T.nilable(::String)) }
  def body; end

  sig { returns(::String) }
  def id; end

  sig { returns(T.nilable(::Translation::Language)) }
  def language; end

  sig { returns(T.nilable(::Translation::Language)) }
  def notes_language; end
end
