# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Graphql::Dashboard::GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl Graphql::Dashboard::GeneratedUrlHelpersModule`.


module Graphql::Dashboard::GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def archive_operation_store_client_operations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def archive_operation_store_operations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def archived_operation_store_client_operations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def archived_operation_store_operations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def delete_all_detailed_traces_traces_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def detailed_traces_trace_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def detailed_traces_traces_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_operation_store_client_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def limiters_limiter_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_operation_store_client_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_client_operations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_client_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_clients_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_index_entries_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_index_entry_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_operation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_operations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def static_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def subscriptions_clear_all_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def subscriptions_subscription_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def subscriptions_topic_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def subscriptions_topics_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def unarchive_operation_store_client_operations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def unarchive_operation_store_operations_url(*args); end
end
