# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Graphql::Dashboard::GeneratedPathHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl Graphql::Dashboard::GeneratedPathHelpersModule`.


module Graphql::Dashboard::GeneratedPathHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def archive_operation_store_client_operations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def archive_operation_store_operations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def archived_operation_store_client_operations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def archived_operation_store_operations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def delete_all_detailed_traces_traces_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def detailed_traces_trace_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def detailed_traces_traces_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_operation_store_client_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def limiters_limiter_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_operation_store_client_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_client_operations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_client_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_clients_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_index_entries_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_index_entry_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_operation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def operation_store_operations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def root_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def static_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def subscriptions_clear_all_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def subscriptions_subscription_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def subscriptions_topic_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def subscriptions_topics_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def unarchive_operation_store_client_operations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def unarchive_operation_store_operations_path(*args); end
end
