# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SpaController`.
# Please instead update this file by running `bin/tapioca dsl SpaController`.


class SpaController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
